/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.model.endpoint;

import javax.annotation.Generated;
import org.apache.camel.model.AbstractEndpointBuilder;
import org.apache.camel.model.EndpointConsumerBuilder;
import org.apache.camel.model.EndpointProducerBuilder;

/**
 * The drill component gives you the ability to quering into apache drill
 * cluster.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.EndpointDslMojo")
public interface DrillEndpointBuilder {


    /**
     * Base class for the Drill component builders.
     */
    public static class DrillCommonBuilder<T extends AbstractEndpointBuilder>
            extends
                AbstractEndpointBuilder<T> {
        DrillCommonBuilder(String path) {
            super("drill", path);
        }
        /**
         * ZooKeeper host name or IP address. Use local instead of a host name
         * or IP address to connect to the local Drillbit. The option is a
         * <code>java.lang.String</code> type.
         */
        public T host(String host) {
            this.properties.put("host", host);
            return (T) this;
        }
        /**
         * Cluster ID
         * https://drill.apache.org/docs/using-the-jdbc-driver/#determining-the-cluster-id. The option is a <code>java.lang.String</code> type.
         */
        public T clusterId(String clusterId) {
            this.properties.put("clusterId", clusterId);
            return (T) this;
        }
        /**
         * Drill directory in ZooKeeper. The option is a
         * <code>java.lang.String</code> type.
         */
        public T directory(String directory) {
            this.properties.put("directory", directory);
            return (T) this;
        }
        /**
         * Connection mode: zk: Zookeeper drillbit: Drillbit direct connection
         * https://drill.apache.org/docs/using-the-jdbc-driver/. The option is a
         * <code>org.apache.camel.component.drill.DrillConnectionMode</code>
         * type.
         */
        public T mode(DrillConnectionMode mode) {
            this.properties.put("mode", mode);
            return (T) this;
        }
        /**
         * Connection mode: zk: Zookeeper drillbit: Drillbit direct connection
         * https://drill.apache.org/docs/using-the-jdbc-driver/. The option will
         * be converted to a
         * <code>org.apache.camel.component.drill.DrillConnectionMode</code>
         * type.
         */
        public T mode(String mode) {
            this.properties.put("mode", mode);
            return (T) this;
        }
        /**
         * ZooKeeper port number. The option is a <code>java.lang.Integer</code>
         * type.
         */
        public T port(Integer port) {
            this.properties.put("port", port);
            return (T) this;
        }
        /**
         * ZooKeeper port number. The option will be converted to a
         * <code>java.lang.Integer</code> type.
         */
        public T port(String port) {
            this.properties.put("port", port);
            return (T) this;
        }
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * is a <code>boolean</code> type.
         */
        public T basicPropertyBinding(boolean basicPropertyBinding) {
            this.properties.put("basicPropertyBinding", basicPropertyBinding);
            return (T) this;
        }
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * will be converted to a <code>boolean</code> type.
         */
        public T basicPropertyBinding(String basicPropertyBinding) {
            this.properties.put("basicPropertyBinding", basicPropertyBinding);
            return (T) this;
        }
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * is a <code>boolean</code> type.
         */
        public T synchronous(boolean synchronous) {
            this.properties.put("synchronous", synchronous);
            return (T) this;
        }
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * will be converted to a <code>boolean</code> type.
         */
        public T synchronous(String synchronous) {
            this.properties.put("synchronous", synchronous);
            return (T) this;
        }
    }

    /**
     * Builder for endpoint producers for the Drill component.
     */
    public static class DrillProducerBuilder
            extends
                DrillCommonBuilder<DrillProducerBuilder>
            implements
                EndpointProducerBuilder {
        public DrillProducerBuilder(String path) {
            super(path);
        }
    }

    /**
     * Proxy enum for
     * <code>org.apache.camel.component.drill.DrillConnectionMode</code> enum.
     */
    public static enum DrillConnectionMode {
        ZK, DRILLBIT;
    }
    /**
     * The drill component gives you the ability to quering into apache drill
     * cluster. Creates a builder to build a producer endpoint for the Drill
     * component.
     */
    public default DrillProducerBuilder toDrill(String path) {
        return new DrillProducerBuilder(path);
    }
}