/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.model.endpoint;

import javax.annotation.Generated;

/**
 * The Ignite ID Generator endpoint is one of camel-ignite endpoints which
 * allows you to interact with Ignite Atomic Sequences and ID Generators.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.EndpointDslMojo")
public class IgniteIdGenEndpoint {


    public static class IgniteIdGenCommon<T extends EndpointConfiguration>
            extends
                EndpointConfiguration<T> {
        private String name;
        private Boolean propagateIncomingBodyIfNoReturnValue;
        private Boolean treatCollectionsAsCacheObjects;
        private Boolean basicPropertyBinding;
        private Boolean synchronous;

        /**
         * The sequence name. The option is a java.lang.String type.
         */
        public T name(String name) {
            this.name = name;
            return (T) this;
        }

        /**
         * Sets whether to propagate the incoming body if the return type of the
         * underlying Ignite operation is void. The option is a boolean type.
         */
        public T propagateIncomingBodyIfNoReturnValue(
                boolean propagateIncomingBodyIfNoReturnValue) {
            this.propagateIncomingBodyIfNoReturnValue = propagateIncomingBodyIfNoReturnValue;
            return (T) this;
        }

        /**
         * Sets whether to treat Collections as cache objects or as Collections
         * of items to insert/update/compute, etc. The option is a boolean type.
         */
        public T treatCollectionsAsCacheObjects(
                boolean treatCollectionsAsCacheObjects) {
            this.treatCollectionsAsCacheObjects = treatCollectionsAsCacheObjects;
            return (T) this;
        }

        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * is a boolean type.
         */
        public T basicPropertyBinding(boolean basicPropertyBinding) {
            this.basicPropertyBinding = basicPropertyBinding;
            return (T) this;
        }

        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * is a boolean type.
         */
        public T synchronous(boolean synchronous) {
            this.synchronous = synchronous;
            return (T) this;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Boolean getPropagateIncomingBodyIfNoReturnValue() {
            return propagateIncomingBodyIfNoReturnValue;
        }

        public void setPropagateIncomingBodyIfNoReturnValue(
                Boolean propagateIncomingBodyIfNoReturnValue) {
            this.propagateIncomingBodyIfNoReturnValue = propagateIncomingBodyIfNoReturnValue;
        }

        public Boolean getTreatCollectionsAsCacheObjects() {
            return treatCollectionsAsCacheObjects;
        }

        public void setTreatCollectionsAsCacheObjects(
                Boolean treatCollectionsAsCacheObjects) {
            this.treatCollectionsAsCacheObjects = treatCollectionsAsCacheObjects;
        }

        public Boolean getBasicPropertyBinding() {
            return basicPropertyBinding;
        }

        public void setBasicPropertyBinding(Boolean basicPropertyBinding) {
            this.basicPropertyBinding = basicPropertyBinding;
        }

        public Boolean getSynchronous() {
            return synchronous;
        }

        public void setSynchronous(Boolean synchronous) {
            this.synchronous = synchronous;
        }
    }

    public static class IgniteIdGenConsumer
            extends
                IgniteIdGenCommon<IgniteIdGenConsumer> {
    }

    public static class IgniteIdGenProducer
            extends
                IgniteIdGenCommon<IgniteIdGenProducer> {
        private Integer batchSize;
        private Long initialValue;
        private IgniteIdGenOperation operation;

        /**
         * The batch size. The option is a java.lang.Integer type.
         */
        public IgniteIdGenProducer batchSize(Integer batchSize) {
            this.batchSize = batchSize;
            return (IgniteIdGenProducer) this;
        }

        /**
         * The initial value. The option is a java.lang.Long type.
         */
        public IgniteIdGenProducer initialValue(Long initialValue) {
            this.initialValue = initialValue;
            return (IgniteIdGenProducer) this;
        }

        /**
         * The operation to invoke on the Ignite ID Generator. Superseded by the
         * IgniteConstants.IGNITE_IDGEN_OPERATION header in the IN message.
         * Possible values: ADD_AND_GET, GET, GET_AND_ADD, GET_AND_INCREMENT,
         * INCREMENT_AND_GET. The option is a
         * org.apache.camel.component.ignite.idgen.IgniteIdGenOperation type.
         */
        public IgniteIdGenProducer operation(IgniteIdGenOperation operation) {
            this.operation = operation;
            return (IgniteIdGenProducer) this;
        }

        public Integer getBatchSize() {
            return batchSize;
        }

        public void setBatchSize(Integer batchSize) {
            this.batchSize = batchSize;
        }

        public Long getInitialValue() {
            return initialValue;
        }

        public void setInitialValue(Long initialValue) {
            this.initialValue = initialValue;
        }

        public IgniteIdGenOperation getOperation() {
            return operation;
        }

        public void setOperation(IgniteIdGenOperation operation) {
            this.operation = operation;
        }
    }

    public static enum IgniteIdGenOperation {
        ADD_AND_GET, GET, GET_AND_ADD, GET_AND_INCREMENT, INCREMENT_AND_GET;
    }
}