/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.model.endpoint;

import javax.annotation.Generated;
import org.apache.camel.ExchangePattern;
import org.apache.camel.spi.ExceptionHandler;

/**
 * The irc component implements an IRC (Internet Relay Chat) transport.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.EndpointDslMojo")
public class IrcEndpoint {


    public static class IrcCommon extends EndpointConfiguration {
        /**
         * Hostname for the IRC chat server. The option is a java.lang.String
         * type.
         */
        private String hostname;
        /**
         * Port number for the IRC chat server. If no port is configured then a
         * default port of either 6667, 6668 or 6669 is used. The option is a
         * int type.
         */
        private Integer port;
        /**
         * Whether to auto re-join when being kicked. The option is a boolean
         * type.
         */
        private Boolean autoRejoin;
        /**
         * Delay in milliseconds before sending commands after the connection is
         * established. The option is a long type.
         */
        private Long commandTimeout;
        /**
         * Sends NAMES command to channel after joining it. onReply has to be
         * true in order to process the result which will have the header value
         * irc.num = '353'. The option is a boolean type.
         */
        private Boolean namesOnJoin;
        /**
         * The nickname used in chat. The option is a java.lang.String type.
         */
        private String nickname;
        /**
         * Use persistent messages. The option is a boolean type.
         */
        @Deprecated
        private Boolean persistent;
        /**
         * The IRC user's actual name. The option is a java.lang.String type.
         */
        private String realname;
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * is a boolean type.
         */
        private Boolean basicPropertyBinding;
        /**
         * Whether or not the server supports color codes. The option is a
         * boolean type.
         */
        private Boolean colors;
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * is a boolean type.
         */
        private Boolean synchronous;
        /**
         * Handle user join events. The option is a boolean type.
         */
        private Boolean onJoin;
        /**
         * Handle kick events. The option is a boolean type.
         */
        private Boolean onKick;
        /**
         * Handle mode change events. The option is a boolean type.
         */
        private Boolean onMode;
        /**
         * Handle nickname change events. The option is a boolean type.
         */
        private Boolean onNick;
        /**
         * Handle user part events. The option is a boolean type.
         */
        private Boolean onPart;
        /**
         * Handle private message events. The option is a boolean type.
         */
        private Boolean onPrivmsg;
        /**
         * Handle user quit events. The option is a boolean type.
         */
        private Boolean onQuit;
        /**
         * Whether or not to handle general responses to commands or
         * informational messages. The option is a boolean type.
         */
        private Boolean onReply;
        /**
         * Handle topic change events. The option is a boolean type.
         */
        private Boolean onTopic;
        /**
         * Your IRC server nickname password. The option is a java.lang.String
         * type.
         */
        private String nickPassword;
        /**
         * The IRC server password. The option is a java.lang.String type.
         */
        private String password;
        /**
         * Used for configuring security using SSL. Reference to a
         * org.apache.camel.support.jsse.SSLContextParameters in the Registry.
         * This reference overrides any configured SSLContextParameters at the
         * component level. Note that this setting overrides the trustManager
         * option. The option is a
         * org.apache.camel.support.jsse.SSLContextParameters type.
         */
        private Object sslContextParameters;
        /**
         * The trust manager used to verify the SSL server's certificate. The
         * option is a org.schwering.irc.lib.ssl.SSLTrustManager type.
         */
        private Object trustManager;
        /**
         * The IRC server user name. The option is a java.lang.String type.
         */
        private String username;

        public String getHostname() {
            return hostname;
        }

        public void setHostname(String hostname) {
            this.hostname = hostname;
        }

        public Integer getPort() {
            return port;
        }

        public void setPort(Integer port) {
            this.port = port;
        }

        public Boolean getAutoRejoin() {
            return autoRejoin;
        }

        public void setAutoRejoin(Boolean autoRejoin) {
            this.autoRejoin = autoRejoin;
        }

        public Long getCommandTimeout() {
            return commandTimeout;
        }

        public void setCommandTimeout(Long commandTimeout) {
            this.commandTimeout = commandTimeout;
        }

        public Boolean getNamesOnJoin() {
            return namesOnJoin;
        }

        public void setNamesOnJoin(Boolean namesOnJoin) {
            this.namesOnJoin = namesOnJoin;
        }

        public String getNickname() {
            return nickname;
        }

        public void setNickname(String nickname) {
            this.nickname = nickname;
        }

        @Deprecated
        public Boolean getPersistent() {
            return persistent;
        }

        @Deprecated
        public void setPersistent(Boolean persistent) {
            this.persistent = persistent;
        }

        public String getRealname() {
            return realname;
        }

        public void setRealname(String realname) {
            this.realname = realname;
        }

        public Boolean getBasicPropertyBinding() {
            return basicPropertyBinding;
        }

        public void setBasicPropertyBinding(Boolean basicPropertyBinding) {
            this.basicPropertyBinding = basicPropertyBinding;
        }

        public Boolean getColors() {
            return colors;
        }

        public void setColors(Boolean colors) {
            this.colors = colors;
        }

        public Boolean getSynchronous() {
            return synchronous;
        }

        public void setSynchronous(Boolean synchronous) {
            this.synchronous = synchronous;
        }

        public Boolean getOnJoin() {
            return onJoin;
        }

        public void setOnJoin(Boolean onJoin) {
            this.onJoin = onJoin;
        }

        public Boolean getOnKick() {
            return onKick;
        }

        public void setOnKick(Boolean onKick) {
            this.onKick = onKick;
        }

        public Boolean getOnMode() {
            return onMode;
        }

        public void setOnMode(Boolean onMode) {
            this.onMode = onMode;
        }

        public Boolean getOnNick() {
            return onNick;
        }

        public void setOnNick(Boolean onNick) {
            this.onNick = onNick;
        }

        public Boolean getOnPart() {
            return onPart;
        }

        public void setOnPart(Boolean onPart) {
            this.onPart = onPart;
        }

        public Boolean getOnPrivmsg() {
            return onPrivmsg;
        }

        public void setOnPrivmsg(Boolean onPrivmsg) {
            this.onPrivmsg = onPrivmsg;
        }

        public Boolean getOnQuit() {
            return onQuit;
        }

        public void setOnQuit(Boolean onQuit) {
            this.onQuit = onQuit;
        }

        public Boolean getOnReply() {
            return onReply;
        }

        public void setOnReply(Boolean onReply) {
            this.onReply = onReply;
        }

        public Boolean getOnTopic() {
            return onTopic;
        }

        public void setOnTopic(Boolean onTopic) {
            this.onTopic = onTopic;
        }

        public String getNickPassword() {
            return nickPassword;
        }

        public void setNickPassword(String nickPassword) {
            this.nickPassword = nickPassword;
        }

        public String getPassword() {
            return password;
        }

        public void setPassword(String password) {
            this.password = password;
        }

        public Object getSslContextParameters() {
            return sslContextParameters;
        }

        public void setSslContextParameters(Object sslContextParameters) {
            this.sslContextParameters = sslContextParameters;
        }

        public Object getTrustManager() {
            return trustManager;
        }

        public void setTrustManager(Object trustManager) {
            this.trustManager = trustManager;
        }

        public String getUsername() {
            return username;
        }

        public void setUsername(String username) {
            this.username = username;
        }
    }

    public static class IrcConsumer extends IrcCommon {
        /**
         * Allows for bridging the consumer to the Camel routing Error Handler,
         * which mean any exceptions occurred while the consumer is trying to
         * pickup incoming messages, or the likes, will now be processed as a
         * message and handled by the routing Error Handler. By default the
         * consumer will use the org.apache.camel.spi.ExceptionHandler to deal
         * with exceptions, that will be logged at WARN or ERROR level and
         * ignored. The option is a boolean type.
         */
        private Boolean bridgeErrorHandler;
        /**
         * To let the consumer use a custom ExceptionHandler. Notice if the
         * option bridgeErrorHandler is enabled then this option is not in use.
         * By default the consumer will deal with exceptions, that will be
         * logged at WARN or ERROR level and ignored. The option is a
         * org.apache.camel.spi.ExceptionHandler type.
         */
        private ExceptionHandler exceptionHandler;
        /**
         * Sets the exchange pattern when the consumer creates an exchange. The
         * option is a org.apache.camel.ExchangePattern type.
         */
        private ExchangePattern exchangePattern;

        public Boolean getBridgeErrorHandler() {
            return bridgeErrorHandler;
        }

        public void setBridgeErrorHandler(Boolean bridgeErrorHandler) {
            this.bridgeErrorHandler = bridgeErrorHandler;
        }

        public ExceptionHandler getExceptionHandler() {
            return exceptionHandler;
        }

        public void setExceptionHandler(ExceptionHandler exceptionHandler) {
            this.exceptionHandler = exceptionHandler;
        }

        public ExchangePattern getExchangePattern() {
            return exchangePattern;
        }

        public void setExchangePattern(ExchangePattern exchangePattern) {
            this.exchangePattern = exchangePattern;
        }
    }

    public static class IrcProducer extends IrcCommon {
    }
}