/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.model.endpoint;

import java.util.Map;
import java.util.Properties;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.annotation.Generated;
import org.apache.camel.ExchangePattern;
import org.apache.camel.LoggingLevel;
import org.apache.camel.model.AbstractEndpointBuilder;
import org.apache.camel.model.EndpointConsumerBuilder;
import org.apache.camel.model.EndpointProducerBuilder;
import org.apache.camel.spi.ExceptionHandler;
import org.apache.camel.spi.HeaderFilterStrategy;
import org.apache.camel.spi.IdempotentRepository;
import org.apache.camel.spi.PollingConsumerPollStrategy;
import org.apache.camel.spi.ScheduledPollConsumerScheduler;

/**
 * To send or receive emails using imap/pop3 or smtp protocols.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.EndpointDslMojo")
public interface MailEndpointBuilder {


    /**
     * Base class for the IMAP component builders.
     */
    public static class MailCommonBuilder<T extends AbstractEndpointBuilder>
            extends
                AbstractEndpointBuilder<T> {
        MailCommonBuilder(String path) {
            super("imap", path);
        }
        /**
         * The mail server host name. The option is a
         * <code>java.lang.String</code> type.
         */
        public T host(String host) {
            this.properties.put("host", host);
            return (T) this;
        }
        /**
         * The port number of the mail server. The option is a <code>int</code>
         * type.
         */
        public T port(int port) {
            this.properties.put("port", port);
            return (T) this;
        }
        /**
         * The port number of the mail server. The option will be converted to a
         * <code>int</code> type.
         */
        public T port(String port) {
            this.properties.put("port", port);
            return (T) this;
        }
        /**
         * Sets additional java mail properties, that will append/override any
         * default properties that is set based on all the other options. This
         * is useful if you need to add some special options but want to keep
         * the others as is. The option is a <code>java.util.Properties</code>
         * type.
         */
        public T additionalJavaMailProperties(
                Properties additionalJavaMailProperties) {
            this.properties.put("additionalJavaMailProperties", additionalJavaMailProperties);
            return (T) this;
        }
        /**
         * Sets additional java mail properties, that will append/override any
         * default properties that is set based on all the other options. This
         * is useful if you need to add some special options but want to keep
         * the others as is. The option will be converted to a
         * <code>java.util.Properties</code> type.
         */
        public T additionalJavaMailProperties(
                String additionalJavaMailProperties) {
            this.properties.put("additionalJavaMailProperties", additionalJavaMailProperties);
            return (T) this;
        }
        /**
         * Specifies the key to an IN message header that contains an
         * alternative email body. For example, if you send emails in text/html
         * format and want to provide an alternative mail body for non-HTML
         * email clients, set the alternative mail body with this key as a
         * header. The option is a <code>java.lang.String</code> type.
         */
        public T alternativeBodyHeader(String alternativeBodyHeader) {
            this.properties.put("alternativeBodyHeader", alternativeBodyHeader);
            return (T) this;
        }
        /**
         * To use a custom AttachmentsContentTransferEncodingResolver to resolve
         * what content-type-encoding to use for attachments. The option is a
         * <code>org.apache.camel.component.mail.AttachmentsContentTransferEncodingResolver</code> type.
         */
        public T attachmentsContentTransferEncodingResolver(
                Object attachmentsContentTransferEncodingResolver) {
            this.properties.put("attachmentsContentTransferEncodingResolver", attachmentsContentTransferEncodingResolver);
            return (T) this;
        }
        /**
         * To use a custom AttachmentsContentTransferEncodingResolver to resolve
         * what content-type-encoding to use for attachments. The option will be
         * converted to a
         * <code>org.apache.camel.component.mail.AttachmentsContentTransferEncodingResolver</code> type.
         */
        public T attachmentsContentTransferEncodingResolver(
                String attachmentsContentTransferEncodingResolver) {
            this.properties.put("attachmentsContentTransferEncodingResolver", attachmentsContentTransferEncodingResolver);
            return (T) this;
        }
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * is a <code>boolean</code> type.
         */
        public T basicPropertyBinding(boolean basicPropertyBinding) {
            this.properties.put("basicPropertyBinding", basicPropertyBinding);
            return (T) this;
        }
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * will be converted to a <code>boolean</code> type.
         */
        public T basicPropertyBinding(String basicPropertyBinding) {
            this.properties.put("basicPropertyBinding", basicPropertyBinding);
            return (T) this;
        }
        /**
         * Sets the binding used to convert from a Camel message to and from a
         * Mail message. The option is a
         * <code>org.apache.camel.component.mail.MailBinding</code> type.
         */
        public T binding(Object binding) {
            this.properties.put("binding", binding);
            return (T) this;
        }
        /**
         * Sets the binding used to convert from a Camel message to and from a
         * Mail message. The option will be converted to a
         * <code>org.apache.camel.component.mail.MailBinding</code> type.
         */
        public T binding(String binding) {
            this.properties.put("binding", binding);
            return (T) this;
        }
        /**
         * The connection timeout in milliseconds. The option is a
         * <code>int</code> type.
         */
        public T connectionTimeout(int connectionTimeout) {
            this.properties.put("connectionTimeout", connectionTimeout);
            return (T) this;
        }
        /**
         * The connection timeout in milliseconds. The option will be converted
         * to a <code>int</code> type.
         */
        public T connectionTimeout(String connectionTimeout) {
            this.properties.put("connectionTimeout", connectionTimeout);
            return (T) this;
        }
        /**
         * The mail message content type. Use text/html for HTML mails. The
         * option is a <code>java.lang.String</code> type.
         */
        public T contentType(String contentType) {
            this.properties.put("contentType", contentType);
            return (T) this;
        }
        /**
         * Resolver to determine Content-Type for file attachments. The option
         * is a <code>org.apache.camel.component.mail.ContentTypeResolver</code>
         * type.
         */
        public T contentTypeResolver(Object contentTypeResolver) {
            this.properties.put("contentTypeResolver", contentTypeResolver);
            return (T) this;
        }
        /**
         * Resolver to determine Content-Type for file attachments. The option
         * will be converted to a
         * <code>org.apache.camel.component.mail.ContentTypeResolver</code>
         * type.
         */
        public T contentTypeResolver(String contentTypeResolver) {
            this.properties.put("contentTypeResolver", contentTypeResolver);
            return (T) this;
        }
        /**
         * Enable debug mode on the underlying mail framework. The SUN Mail
         * framework logs the debug messages to System.out by default. The
         * option is a <code>boolean</code> type.
         */
        public T debugMode(boolean debugMode) {
            this.properties.put("debugMode", debugMode);
            return (T) this;
        }
        /**
         * Enable debug mode on the underlying mail framework. The SUN Mail
         * framework logs the debug messages to System.out by default. The
         * option will be converted to a <code>boolean</code> type.
         */
        public T debugMode(String debugMode) {
            this.properties.put("debugMode", debugMode);
            return (T) this;
        }
        /**
         * To use a custom org.apache.camel.spi.HeaderFilterStrategy to filter
         * headers. The option is a
         * <code>org.apache.camel.spi.HeaderFilterStrategy</code> type.
         */
        public T headerFilterStrategy(HeaderFilterStrategy headerFilterStrategy) {
            this.properties.put("headerFilterStrategy", headerFilterStrategy);
            return (T) this;
        }
        /**
         * To use a custom org.apache.camel.spi.HeaderFilterStrategy to filter
         * headers. The option will be converted to a
         * <code>org.apache.camel.spi.HeaderFilterStrategy</code> type.
         */
        public T headerFilterStrategy(String headerFilterStrategy) {
            this.properties.put("headerFilterStrategy", headerFilterStrategy);
            return (T) this;
        }
        /**
         * Option to let Camel ignore unsupported charset in the local JVM when
         * sending mails. If the charset is unsupported then charset=XXX (where
         * XXX represents the unsupported charset) is removed from the
         * content-type and it relies on the platform default instead. The
         * option is a <code>boolean</code> type.
         */
        public T ignoreUnsupportedCharset(boolean ignoreUnsupportedCharset) {
            this.properties.put("ignoreUnsupportedCharset", ignoreUnsupportedCharset);
            return (T) this;
        }
        /**
         * Option to let Camel ignore unsupported charset in the local JVM when
         * sending mails. If the charset is unsupported then charset=XXX (where
         * XXX represents the unsupported charset) is removed from the
         * content-type and it relies on the platform default instead. The
         * option will be converted to a <code>boolean</code> type.
         */
        public T ignoreUnsupportedCharset(String ignoreUnsupportedCharset) {
            this.properties.put("ignoreUnsupportedCharset", ignoreUnsupportedCharset);
            return (T) this;
        }
        /**
         * Option to let Camel ignore unsupported charset in the local JVM when
         * sending mails. If the charset is unsupported then charset=XXX (where
         * XXX represents the unsupported charset) is removed from the
         * content-type and it relies on the platform default instead. The
         * option is a <code>boolean</code> type.
         */
        public T ignoreUriScheme(boolean ignoreUriScheme) {
            this.properties.put("ignoreUriScheme", ignoreUriScheme);
            return (T) this;
        }
        /**
         * Option to let Camel ignore unsupported charset in the local JVM when
         * sending mails. If the charset is unsupported then charset=XXX (where
         * XXX represents the unsupported charset) is removed from the
         * content-type and it relies on the platform default instead. The
         * option will be converted to a <code>boolean</code> type.
         */
        public T ignoreUriScheme(String ignoreUriScheme) {
            this.properties.put("ignoreUriScheme", ignoreUriScheme);
            return (T) this;
        }
        /**
         * Specifies the mail session that camel should use for all mail
         * interactions. Useful in scenarios where mail sessions are created and
         * managed by some other resource, such as a JavaEE container. If this
         * is not specified, Camel automatically creates the mail session for
         * you. The option is a <code>javax.mail.Session</code> type.
         */
        public T session(Object session) {
            this.properties.put("session", session);
            return (T) this;
        }
        /**
         * Specifies the mail session that camel should use for all mail
         * interactions. Useful in scenarios where mail sessions are created and
         * managed by some other resource, such as a JavaEE container. If this
         * is not specified, Camel automatically creates the mail session for
         * you. The option will be converted to a
         * <code>javax.mail.Session</code> type.
         */
        public T session(String session) {
            this.properties.put("session", session);
            return (T) this;
        }
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * is a <code>boolean</code> type.
         */
        public T synchronous(boolean synchronous) {
            this.properties.put("synchronous", synchronous);
            return (T) this;
        }
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * will be converted to a <code>boolean</code> type.
         */
        public T synchronous(String synchronous) {
            this.properties.put("synchronous", synchronous);
            return (T) this;
        }
        /**
         * Whether to use disposition inline or attachment. The option is a
         * <code>boolean</code> type.
         */
        public T useInlineAttachments(boolean useInlineAttachments) {
            this.properties.put("useInlineAttachments", useInlineAttachments);
            return (T) this;
        }
        /**
         * Whether to use disposition inline or attachment. The option will be
         * converted to a <code>boolean</code> type.
         */
        public T useInlineAttachments(String useInlineAttachments) {
            this.properties.put("useInlineAttachments", useInlineAttachments);
            return (T) this;
        }
        /**
         * To use a dummy security setting for trusting all certificates. Should
         * only be used for development mode, and not production. The option is
         * a <code>boolean</code> type.
         */
        public T dummyTrustManager(boolean dummyTrustManager) {
            this.properties.put("dummyTrustManager", dummyTrustManager);
            return (T) this;
        }
        /**
         * To use a dummy security setting for trusting all certificates. Should
         * only be used for development mode, and not production. The option
         * will be converted to a <code>boolean</code> type.
         */
        public T dummyTrustManager(String dummyTrustManager) {
            this.properties.put("dummyTrustManager", dummyTrustManager);
            return (T) this;
        }
        /**
         * The password for login. The option is a <code>java.lang.String</code>
         * type.
         */
        public T password(String password) {
            this.properties.put("password", password);
            return (T) this;
        }
        /**
         * To configure security using SSLContextParameters. The option is a
         * <code>org.apache.camel.support.jsse.SSLContextParameters</code> type.
         */
        public T sslContextParameters(Object sslContextParameters) {
            this.properties.put("sslContextParameters", sslContextParameters);
            return (T) this;
        }
        /**
         * To configure security using SSLContextParameters. The option will be
         * converted to a
         * <code>org.apache.camel.support.jsse.SSLContextParameters</code> type.
         */
        public T sslContextParameters(String sslContextParameters) {
            this.properties.put("sslContextParameters", sslContextParameters);
            return (T) this;
        }
        /**
         * The username for login. The option is a <code>java.lang.String</code>
         * type.
         */
        public T username(String username) {
            this.properties.put("username", username);
            return (T) this;
        }
    }

    /**
     * Builder for endpoint consumers for the IMAP component.
     */
    public static class MailConsumerBuilder
            extends
                MailCommonBuilder<MailConsumerBuilder>
            implements
                EndpointConsumerBuilder {
        public MailConsumerBuilder(String path) {
            super(path);
        }
        /**
         * Allows for bridging the consumer to the Camel routing Error Handler,
         * which mean any exceptions occurred while the consumer is trying to
         * pickup incoming messages, or the likes, will now be processed as a
         * message and handled by the routing Error Handler. By default the
         * consumer will use the org.apache.camel.spi.ExceptionHandler to deal
         * with exceptions, that will be logged at WARN or ERROR level and
         * ignored. The option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder bridgeErrorHandler(boolean bridgeErrorHandler) {
            this.properties.put("bridgeErrorHandler", bridgeErrorHandler);
            return (MailConsumerBuilder) this;
        }
        /**
         * Allows for bridging the consumer to the Camel routing Error Handler,
         * which mean any exceptions occurred while the consumer is trying to
         * pickup incoming messages, or the likes, will now be processed as a
         * message and handled by the routing Error Handler. By default the
         * consumer will use the org.apache.camel.spi.ExceptionHandler to deal
         * with exceptions, that will be logged at WARN or ERROR level and
         * ignored. The option will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder bridgeErrorHandler(String bridgeErrorHandler) {
            this.properties.put("bridgeErrorHandler", bridgeErrorHandler);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the consumer should close the folder after polling. Setting
         * this option to false and having disconnect=false as well, then the
         * consumer keep the folder open between polls. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder closeFolder(boolean closeFolder) {
            this.properties.put("closeFolder", closeFolder);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the consumer should close the folder after polling. Setting
         * this option to false and having disconnect=false as well, then the
         * consumer keep the folder open between polls. The option will be
         * converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder closeFolder(String closeFolder) {
            this.properties.put("closeFolder", closeFolder);
            return (MailConsumerBuilder) this;
        }
        /**
         * After processing a mail message, it can be copied to a mail folder
         * with the given name. You can override this configuration value, with
         * a header with the key copyTo, allowing you to copy messages to folder
         * names configured at runtime. The option is a
         * <code>java.lang.String</code> type.
         */
        public MailConsumerBuilder copyTo(String copyTo) {
            this.properties.put("copyTo", copyTo);
            return (MailConsumerBuilder) this;
        }
        /**
         * Deletes the messages after they have been processed. This is done by
         * setting the DELETED flag on the mail message. If false, the SEEN flag
         * is set instead. As of Camel 2.10 you can override this configuration
         * option by setting a header with the key delete to determine if the
         * mail should be deleted or not. The option is a <code>boolean</code>
         * type.
         */
        public MailConsumerBuilder delete(boolean delete) {
            this.properties.put("delete", delete);
            return (MailConsumerBuilder) this;
        }
        /**
         * Deletes the messages after they have been processed. This is done by
         * setting the DELETED flag on the mail message. If false, the SEEN flag
         * is set instead. As of Camel 2.10 you can override this configuration
         * option by setting a header with the key delete to determine if the
         * mail should be deleted or not. The option will be converted to a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder delete(String delete) {
            this.properties.put("delete", delete);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the consumer should disconnect after polling. If enabled this
         * forces Camel to connect on each poll. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder disconnect(boolean disconnect) {
            this.properties.put("disconnect", disconnect);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the consumer should disconnect after polling. If enabled this
         * forces Camel to connect on each poll. The option will be converted to
         * a <code>boolean</code> type.
         */
        public MailConsumerBuilder disconnect(String disconnect) {
            this.properties.put("disconnect", disconnect);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the mail consumer cannot retrieve a given mail message, then this
         * option allows to handle the caused exception by the consumer's error
         * handler. By enable the bridge error handler on the consumer, then the
         * Camel routing error handler can handle the exception instead. The
         * default behavior would be the consumer throws an exception and no
         * mails from the batch would be able to be routed by Camel. The option
         * is a <code>boolean</code> type.
         */
        public MailConsumerBuilder handleFailedMessage(
                boolean handleFailedMessage) {
            this.properties.put("handleFailedMessage", handleFailedMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the mail consumer cannot retrieve a given mail message, then this
         * option allows to handle the caused exception by the consumer's error
         * handler. By enable the bridge error handler on the consumer, then the
         * Camel routing error handler can handle the exception instead. The
         * default behavior would be the consumer throws an exception and no
         * mails from the batch would be able to be routed by Camel. The option
         * will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder handleFailedMessage(
                String handleFailedMessage) {
            this.properties.put("handleFailedMessage", handleFailedMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * Specifies the maximum number of messages to gather per poll. By
         * default, no maximum is set. Can be used to set a limit of e.g. 1000
         * to avoid downloading thousands of files when the server starts up.
         * Set a value of 0 or negative to disable this option. The option is a
         * <code>int</code> type.
         */
        public MailConsumerBuilder maxMessagesPerPoll(int maxMessagesPerPoll) {
            this.properties.put("maxMessagesPerPoll", maxMessagesPerPoll);
            return (MailConsumerBuilder) this;
        }
        /**
         * Specifies the maximum number of messages to gather per poll. By
         * default, no maximum is set. Can be used to set a limit of e.g. 1000
         * to avoid downloading thousands of files when the server starts up.
         * Set a value of 0 or negative to disable this option. The option will
         * be converted to a <code>int</code> type.
         */
        public MailConsumerBuilder maxMessagesPerPoll(String maxMessagesPerPoll) {
            this.properties.put("maxMessagesPerPoll", maxMessagesPerPoll);
            return (MailConsumerBuilder) this;
        }
        /**
         * This option enables transparent MIME decoding and unfolding for mail
         * headers. The option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder mimeDecodeHeaders(boolean mimeDecodeHeaders) {
            this.properties.put("mimeDecodeHeaders", mimeDecodeHeaders);
            return (MailConsumerBuilder) this;
        }
        /**
         * This option enables transparent MIME decoding and unfolding for mail
         * headers. The option will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder mimeDecodeHeaders(String mimeDecodeHeaders) {
            this.properties.put("mimeDecodeHeaders", mimeDecodeHeaders);
            return (MailConsumerBuilder) this;
        }
        /**
         * Will mark the javax.mail.Message as peeked before processing the mail
         * message. This applies to IMAPMessage messages types only. By using
         * peek the mail will not be eager marked as SEEN on the mail server,
         * which allows us to rollback the mail message if there is an error
         * processing in Camel. The option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder peek(boolean peek) {
            this.properties.put("peek", peek);
            return (MailConsumerBuilder) this;
        }
        /**
         * Will mark the javax.mail.Message as peeked before processing the mail
         * message. This applies to IMAPMessage messages types only. By using
         * peek the mail will not be eager marked as SEEN on the mail server,
         * which allows us to rollback the mail message if there is an error
         * processing in Camel. The option will be converted to a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder peek(String peek) {
            this.properties.put("peek", peek);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the polling consumer did not poll any files, you can enable this
         * option to send an empty message (no body) instead. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder sendEmptyMessageWhenIdle(
                boolean sendEmptyMessageWhenIdle) {
            this.properties.put("sendEmptyMessageWhenIdle", sendEmptyMessageWhenIdle);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the polling consumer did not poll any files, you can enable this
         * option to send an empty message (no body) instead. The option will be
         * converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder sendEmptyMessageWhenIdle(
                String sendEmptyMessageWhenIdle) {
            this.properties.put("sendEmptyMessageWhenIdle", sendEmptyMessageWhenIdle);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the mail consumer cannot retrieve a given mail message, then this
         * option allows to skip the message and move on to retrieve the next
         * mail message. The default behavior would be the consumer throws an
         * exception and no mails from the batch would be able to be routed by
         * Camel. The option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder skipFailedMessage(boolean skipFailedMessage) {
            this.properties.put("skipFailedMessage", skipFailedMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * If the mail consumer cannot retrieve a given mail message, then this
         * option allows to skip the message and move on to retrieve the next
         * mail message. The default behavior would be the consumer throws an
         * exception and no mails from the batch would be able to be routed by
         * Camel. The option will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder skipFailedMessage(String skipFailedMessage) {
            this.properties.put("skipFailedMessage", skipFailedMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether to limit by unseen mails only. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder unseen(boolean unseen) {
            this.properties.put("unseen", unseen);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether to limit by unseen mails only. The option will be converted
         * to a <code>boolean</code> type.
         */
        public MailConsumerBuilder unseen(String unseen) {
            this.properties.put("unseen", unseen);
            return (MailConsumerBuilder) this;
        }
        /**
         * To let the consumer use a custom ExceptionHandler. Notice if the
         * option bridgeErrorHandler is enabled then this option is not in use.
         * By default the consumer will deal with exceptions, that will be
         * logged at WARN or ERROR level and ignored. The option is a
         * <code>org.apache.camel.spi.ExceptionHandler</code> type.
         */
        public MailConsumerBuilder exceptionHandler(
                ExceptionHandler exceptionHandler) {
            this.properties.put("exceptionHandler", exceptionHandler);
            return (MailConsumerBuilder) this;
        }
        /**
         * To let the consumer use a custom ExceptionHandler. Notice if the
         * option bridgeErrorHandler is enabled then this option is not in use.
         * By default the consumer will deal with exceptions, that will be
         * logged at WARN or ERROR level and ignored. The option will be
         * converted to a <code>org.apache.camel.spi.ExceptionHandler</code>
         * type.
         */
        public MailConsumerBuilder exceptionHandler(String exceptionHandler) {
            this.properties.put("exceptionHandler", exceptionHandler);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sets the exchange pattern when the consumer creates an exchange. The
         * option is a <code>org.apache.camel.ExchangePattern</code> type.
         */
        public MailConsumerBuilder exchangePattern(
                ExchangePattern exchangePattern) {
            this.properties.put("exchangePattern", exchangePattern);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sets the exchange pattern when the consumer creates an exchange. The
         * option will be converted to a
         * <code>org.apache.camel.ExchangePattern</code> type.
         */
        public MailConsumerBuilder exchangePattern(String exchangePattern) {
            this.properties.put("exchangePattern", exchangePattern);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sets the maximum number of messages to consume during a poll. This
         * can be used to avoid overloading a mail server, if a mailbox folder
         * contains a lot of messages. Default value of -1 means no fetch size
         * and all messages will be consumed. Setting the value to 0 is a
         * special corner case, where Camel will not consume any messages at
         * all. The option is a <code>int</code> type.
         */
        public MailConsumerBuilder fetchSize(int fetchSize) {
            this.properties.put("fetchSize", fetchSize);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sets the maximum number of messages to consume during a poll. This
         * can be used to avoid overloading a mail server, if a mailbox folder
         * contains a lot of messages. Default value of -1 means no fetch size
         * and all messages will be consumed. Setting the value to 0 is a
         * special corner case, where Camel will not consume any messages at
         * all. The option will be converted to a <code>int</code> type.
         */
        public MailConsumerBuilder fetchSize(String fetchSize) {
            this.properties.put("fetchSize", fetchSize);
            return (MailConsumerBuilder) this;
        }
        /**
         * The folder to poll. The option is a <code>java.lang.String</code>
         * type.
         */
        public MailConsumerBuilder folderName(String folderName) {
            this.properties.put("folderName", folderName);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable MailUidGenerator that allows to use custom logic to
         * generate UUID of the mail message. The option is a
         * <code>org.apache.camel.component.mail.MailUidGenerator</code> type.
         */
        public MailConsumerBuilder mailUidGenerator(Object mailUidGenerator) {
            this.properties.put("mailUidGenerator", mailUidGenerator);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable MailUidGenerator that allows to use custom logic to
         * generate UUID of the mail message. The option will be converted to a
         * <code>org.apache.camel.component.mail.MailUidGenerator</code> type.
         */
        public MailConsumerBuilder mailUidGenerator(String mailUidGenerator) {
            this.properties.put("mailUidGenerator", mailUidGenerator);
            return (MailConsumerBuilder) this;
        }
        /**
         * Specifies whether Camel should map the received mail message to Camel
         * body/headers. If set to true, the body of the mail message is mapped
         * to the body of the Camel IN message and the mail headers are mapped
         * to IN headers. If this option is set to false then the IN message
         * contains a raw javax.mail.Message. You can retrieve this raw message
         * by calling exchange.getIn().getBody(javax.mail.Message.class). The
         * option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder mapMailMessage(boolean mapMailMessage) {
            this.properties.put("mapMailMessage", mapMailMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * Specifies whether Camel should map the received mail message to Camel
         * body/headers. If set to true, the body of the mail message is mapped
         * to the body of the Camel IN message and the mail headers are mapped
         * to IN headers. If this option is set to false then the IN message
         * contains a raw javax.mail.Message. You can retrieve this raw message
         * by calling exchange.getIn().getBody(javax.mail.Message.class). The
         * option will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder mapMailMessage(String mapMailMessage) {
            this.properties.put("mapMailMessage", mapMailMessage);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing
         * you to provide your custom implementation to control error handling
         * usually occurred during the poll operation before an Exchange have
         * been created and being routed in Camel. The option is a
         * <code>org.apache.camel.spi.PollingConsumerPollStrategy</code> type.
         */
        public MailConsumerBuilder pollStrategy(
                PollingConsumerPollStrategy pollStrategy) {
            this.properties.put("pollStrategy", pollStrategy);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing
         * you to provide your custom implementation to control error handling
         * usually occurred during the poll operation before an Exchange have
         * been created and being routed in Camel. The option will be converted
         * to a <code>org.apache.camel.spi.PollingConsumerPollStrategy</code>
         * type.
         */
        public MailConsumerBuilder pollStrategy(String pollStrategy) {
            this.properties.put("pollStrategy", pollStrategy);
            return (MailConsumerBuilder) this;
        }
        /**
         * Refers to an MailBoxPostProcessAction for doing post processing tasks
         * on the mailbox once the normal processing ended. The option is a
         * <code>org.apache.camel.component.mail.MailBoxPostProcessAction</code>
         * type.
         */
        public MailConsumerBuilder postProcessAction(Object postProcessAction) {
            this.properties.put("postProcessAction", postProcessAction);
            return (MailConsumerBuilder) this;
        }
        /**
         * Refers to an MailBoxPostProcessAction for doing post processing tasks
         * on the mailbox once the normal processing ended. The option will be
         * converted to a
         * <code>org.apache.camel.component.mail.MailBoxPostProcessAction</code>
         * type.
         */
        public MailConsumerBuilder postProcessAction(String postProcessAction) {
            this.properties.put("postProcessAction", postProcessAction);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable repository org.apache.camel.spi.IdempotentRepository
         * which allows to cluster consuming from the same mailbox, and let the
         * repository coordinate whether a mail message is valid for the
         * consumer to process. By default no repository is in use. The option
         * is a <code>org.apache.camel.spi.IdempotentRepository</code> type.
         */
        public MailConsumerBuilder idempotentRepository(
                IdempotentRepository idempotentRepository) {
            this.properties.put("idempotentRepository", idempotentRepository);
            return (MailConsumerBuilder) this;
        }
        /**
         * A pluggable repository org.apache.camel.spi.IdempotentRepository
         * which allows to cluster consuming from the same mailbox, and let the
         * repository coordinate whether a mail message is valid for the
         * consumer to process. By default no repository is in use. The option
         * will be converted to a
         * <code>org.apache.camel.spi.IdempotentRepository</code> type.
         */
        public MailConsumerBuilder idempotentRepository(
                String idempotentRepository) {
            this.properties.put("idempotentRepository", idempotentRepository);
            return (MailConsumerBuilder) this;
        }
        /**
         * When using idempotent repository, then when the mail message has been
         * successfully processed and is committed, should the message id be
         * removed from the idempotent repository (default) or be kept in the
         * repository. By default its assumed the message id is unique and has
         * no value to be kept in the repository, because the mail message will
         * be marked as seen/moved or deleted to prevent it from being consumed
         * again. And therefore having the message id stored in the idempotent
         * repository has little value. However this option allows to store the
         * message id, for whatever reason you may have. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder idempotentRepositoryRemoveOnCommit(
                boolean idempotentRepositoryRemoveOnCommit) {
            this.properties.put("idempotentRepositoryRemoveOnCommit", idempotentRepositoryRemoveOnCommit);
            return (MailConsumerBuilder) this;
        }
        /**
         * When using idempotent repository, then when the mail message has been
         * successfully processed and is committed, should the message id be
         * removed from the idempotent repository (default) or be kept in the
         * repository. By default its assumed the message id is unique and has
         * no value to be kept in the repository, because the mail message will
         * be marked as seen/moved or deleted to prevent it from being consumed
         * again. And therefore having the message id stored in the idempotent
         * repository has little value. However this option allows to store the
         * message id, for whatever reason you may have. The option will be
         * converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder idempotentRepositoryRemoveOnCommit(
                String idempotentRepositoryRemoveOnCommit) {
            this.properties.put("idempotentRepositoryRemoveOnCommit", idempotentRepositoryRemoveOnCommit);
            return (MailConsumerBuilder) this;
        }
        /**
         * Refers to a javax.mail.search.SearchTerm which allows to filter mails
         * based on search criteria such as subject, body, from, sent after a
         * certain date etc. The option is a
         * <code>javax.mail.search.SearchTerm</code> type.
         */
        public MailConsumerBuilder searchTerm(Object searchTerm) {
            this.properties.put("searchTerm", searchTerm);
            return (MailConsumerBuilder) this;
        }
        /**
         * Refers to a javax.mail.search.SearchTerm which allows to filter mails
         * based on search criteria such as subject, body, from, sent after a
         * certain date etc. The option will be converted to a
         * <code>javax.mail.search.SearchTerm</code> type.
         */
        public MailConsumerBuilder searchTerm(String searchTerm) {
            this.properties.put("searchTerm", searchTerm);
            return (MailConsumerBuilder) this;
        }
        /**
         * The number of subsequent error polls (failed due some error) that
         * should happen before the backoffMultipler should kick-in. The option
         * is a <code>int</code> type.
         */
        public MailConsumerBuilder backoffErrorThreshold(
                int backoffErrorThreshold) {
            this.properties.put("backoffErrorThreshold", backoffErrorThreshold);
            return (MailConsumerBuilder) this;
        }
        /**
         * The number of subsequent error polls (failed due some error) that
         * should happen before the backoffMultipler should kick-in. The option
         * will be converted to a <code>int</code> type.
         */
        public MailConsumerBuilder backoffErrorThreshold(
                String backoffErrorThreshold) {
            this.properties.put("backoffErrorThreshold", backoffErrorThreshold);
            return (MailConsumerBuilder) this;
        }
        /**
         * The number of subsequent idle polls that should happen before the
         * backoffMultipler should kick-in. The option is a <code>int</code>
         * type.
         */
        public MailConsumerBuilder backoffIdleThreshold(int backoffIdleThreshold) {
            this.properties.put("backoffIdleThreshold", backoffIdleThreshold);
            return (MailConsumerBuilder) this;
        }
        /**
         * The number of subsequent idle polls that should happen before the
         * backoffMultipler should kick-in. The option will be converted to a
         * <code>int</code> type.
         */
        public MailConsumerBuilder backoffIdleThreshold(
                String backoffIdleThreshold) {
            this.properties.put("backoffIdleThreshold", backoffIdleThreshold);
            return (MailConsumerBuilder) this;
        }
        /**
         * To let the scheduled polling consumer backoff if there has been a
         * number of subsequent idles/errors in a row. The multiplier is then
         * the number of polls that will be skipped before the next actual
         * attempt is happening again. When this option is in use then
         * backoffIdleThreshold and/or backoffErrorThreshold must also be
         * configured. The option is a <code>int</code> type.
         */
        public MailConsumerBuilder backoffMultiplier(int backoffMultiplier) {
            this.properties.put("backoffMultiplier", backoffMultiplier);
            return (MailConsumerBuilder) this;
        }
        /**
         * To let the scheduled polling consumer backoff if there has been a
         * number of subsequent idles/errors in a row. The multiplier is then
         * the number of polls that will be skipped before the next actual
         * attempt is happening again. When this option is in use then
         * backoffIdleThreshold and/or backoffErrorThreshold must also be
         * configured. The option will be converted to a <code>int</code> type.
         */
        public MailConsumerBuilder backoffMultiplier(String backoffMultiplier) {
            this.properties.put("backoffMultiplier", backoffMultiplier);
            return (MailConsumerBuilder) this;
        }
        /**
         * Milliseconds before the next poll. The option is a <code>long</code>
         * type.
         */
        public MailConsumerBuilder delay(long delay) {
            this.properties.put("delay", delay);
            return (MailConsumerBuilder) this;
        }
        /**
         * Milliseconds before the next poll. The option will be converted to a
         * <code>long</code> type.
         */
        public MailConsumerBuilder delay(String delay) {
            this.properties.put("delay", delay);
            return (MailConsumerBuilder) this;
        }
        /**
         * If greedy is enabled, then the ScheduledPollConsumer will run
         * immediately again, if the previous run polled 1 or more messages. The
         * option is a <code>boolean</code> type.
         */
        public MailConsumerBuilder greedy(boolean greedy) {
            this.properties.put("greedy", greedy);
            return (MailConsumerBuilder) this;
        }
        /**
         * If greedy is enabled, then the ScheduledPollConsumer will run
         * immediately again, if the previous run polled 1 or more messages. The
         * option will be converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder greedy(String greedy) {
            this.properties.put("greedy", greedy);
            return (MailConsumerBuilder) this;
        }
        /**
         * Milliseconds before the first poll starts. You can also specify time
         * values using units, such as 60s (60 seconds), 5m30s (5 minutes and 30
         * seconds), and 1h (1 hour). The option is a <code>long</code> type.
         */
        public MailConsumerBuilder initialDelay(long initialDelay) {
            this.properties.put("initialDelay", initialDelay);
            return (MailConsumerBuilder) this;
        }
        /**
         * Milliseconds before the first poll starts. You can also specify time
         * values using units, such as 60s (60 seconds), 5m30s (5 minutes and 30
         * seconds), and 1h (1 hour). The option will be converted to a
         * <code>long</code> type.
         */
        public MailConsumerBuilder initialDelay(String initialDelay) {
            this.properties.put("initialDelay", initialDelay);
            return (MailConsumerBuilder) this;
        }
        /**
         * The consumer logs a start/complete log line when it polls. This
         * option allows you to configure the logging level for that. The option
         * is a <code>org.apache.camel.LoggingLevel</code> type.
         */
        public MailConsumerBuilder runLoggingLevel(LoggingLevel runLoggingLevel) {
            this.properties.put("runLoggingLevel", runLoggingLevel);
            return (MailConsumerBuilder) this;
        }
        /**
         * The consumer logs a start/complete log line when it polls. This
         * option allows you to configure the logging level for that. The option
         * will be converted to a <code>org.apache.camel.LoggingLevel</code>
         * type.
         */
        public MailConsumerBuilder runLoggingLevel(String runLoggingLevel) {
            this.properties.put("runLoggingLevel", runLoggingLevel);
            return (MailConsumerBuilder) this;
        }
        /**
         * Allows for configuring a custom/shared thread pool to use for the
         * consumer. By default each consumer has its own single threaded thread
         * pool. The option is a
         * <code>java.util.concurrent.ScheduledExecutorService</code> type.
         */
        public MailConsumerBuilder scheduledExecutorService(
                ScheduledExecutorService scheduledExecutorService) {
            this.properties.put("scheduledExecutorService", scheduledExecutorService);
            return (MailConsumerBuilder) this;
        }
        /**
         * Allows for configuring a custom/shared thread pool to use for the
         * consumer. By default each consumer has its own single threaded thread
         * pool. The option will be converted to a
         * <code>java.util.concurrent.ScheduledExecutorService</code> type.
         */
        public MailConsumerBuilder scheduledExecutorService(
                String scheduledExecutorService) {
            this.properties.put("scheduledExecutorService", scheduledExecutorService);
            return (MailConsumerBuilder) this;
        }
        /**
         * To use a cron scheduler from either camel-spring or camel-quartz2
         * component. The option is a
         * <code>org.apache.camel.spi.ScheduledPollConsumerScheduler</code>
         * type.
         */
        public MailConsumerBuilder scheduler(
                ScheduledPollConsumerScheduler scheduler) {
            this.properties.put("scheduler", scheduler);
            return (MailConsumerBuilder) this;
        }
        /**
         * To use a cron scheduler from either camel-spring or camel-quartz2
         * component. The option will be converted to a
         * <code>org.apache.camel.spi.ScheduledPollConsumerScheduler</code>
         * type.
         */
        public MailConsumerBuilder scheduler(String scheduler) {
            this.properties.put("scheduler", scheduler);
            return (MailConsumerBuilder) this;
        }
        /**
         * To configure additional properties when using a custom scheduler or
         * any of the Quartz2, Spring based scheduler. The option is a
         * <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code>
         * type.
         */
        public MailConsumerBuilder schedulerProperties(
                Map<String, Object> schedulerProperties) {
            this.properties.put("schedulerProperties", schedulerProperties);
            return (MailConsumerBuilder) this;
        }
        /**
         * To configure additional properties when using a custom scheduler or
         * any of the Quartz2, Spring based scheduler. The option will be
         * converted to a <code>java.util.Map&lt;java.lang.String,
         * java.lang.Object&gt;</code> type.
         */
        public MailConsumerBuilder schedulerProperties(
                String schedulerProperties) {
            this.properties.put("schedulerProperties", schedulerProperties);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the scheduler should be auto started. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder startScheduler(boolean startScheduler) {
            this.properties.put("startScheduler", startScheduler);
            return (MailConsumerBuilder) this;
        }
        /**
         * Whether the scheduler should be auto started. The option will be
         * converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder startScheduler(String startScheduler) {
            this.properties.put("startScheduler", startScheduler);
            return (MailConsumerBuilder) this;
        }
        /**
         * Time unit for initialDelay and delay options. The option is a
         * <code>java.util.concurrent.TimeUnit</code> type.
         */
        public MailConsumerBuilder timeUnit(TimeUnit timeUnit) {
            this.properties.put("timeUnit", timeUnit);
            return (MailConsumerBuilder) this;
        }
        /**
         * Time unit for initialDelay and delay options. The option will be
         * converted to a <code>java.util.concurrent.TimeUnit</code> type.
         */
        public MailConsumerBuilder timeUnit(String timeUnit) {
            this.properties.put("timeUnit", timeUnit);
            return (MailConsumerBuilder) this;
        }
        /**
         * Controls if fixed delay or fixed rate is used. See
         * ScheduledExecutorService in JDK for details. The option is a
         * <code>boolean</code> type.
         */
        public MailConsumerBuilder useFixedDelay(boolean useFixedDelay) {
            this.properties.put("useFixedDelay", useFixedDelay);
            return (MailConsumerBuilder) this;
        }
        /**
         * Controls if fixed delay or fixed rate is used. See
         * ScheduledExecutorService in JDK for details. The option will be
         * converted to a <code>boolean</code> type.
         */
        public MailConsumerBuilder useFixedDelay(String useFixedDelay) {
            this.properties.put("useFixedDelay", useFixedDelay);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sorting order for messages. Only natively supported for IMAP.
         * Emulated to some degree when using POP3 or when IMAP server does not
         * have the SORT capability. The option is a
         * <code>com.sun.mail.imap.SortTerm[]</code> type.
         */
        public MailConsumerBuilder sortTerm(Object[] sortTerm) {
            this.properties.put("sortTerm", sortTerm);
            return (MailConsumerBuilder) this;
        }
        /**
         * Sorting order for messages. Only natively supported for IMAP.
         * Emulated to some degree when using POP3 or when IMAP server does not
         * have the SORT capability. The option will be converted to a
         * <code>com.sun.mail.imap.SortTerm[]</code> type.
         */
        public MailConsumerBuilder sortTerm(String sortTerm) {
            this.properties.put("sortTerm", sortTerm);
            return (MailConsumerBuilder) this;
        }
    }

    /**
     * Builder for endpoint producers for the IMAP component.
     */
    public static class MailProducerBuilder
            extends
                MailCommonBuilder<MailProducerBuilder>
            implements
                EndpointProducerBuilder {
        public MailProducerBuilder(String path) {
            super(path);
        }
        /**
         * Sets the BCC email address. Separate multiple email addresses with
         * comma. The option is a <code>java.lang.String</code> type.
         */
        public MailProducerBuilder bcc(String bcc) {
            this.properties.put("bcc", bcc);
            return (MailProducerBuilder) this;
        }
        /**
         * Sets the CC email address. Separate multiple email addresses with
         * comma. The option is a <code>java.lang.String</code> type.
         */
        public MailProducerBuilder cc(String cc) {
            this.properties.put("cc", cc);
            return (MailProducerBuilder) this;
        }
        /**
         * The from email address. The option is a <code>java.lang.String</code>
         * type.
         */
        public MailProducerBuilder from(String from) {
            this.properties.put("from", from);
            return (MailProducerBuilder) this;
        }
        /**
         * The Reply-To recipients (the receivers of the response mail).
         * Separate multiple email addresses with a comma. The option is a
         * <code>java.lang.String</code> type.
         */
        public MailProducerBuilder replyTo(String replyTo) {
            this.properties.put("replyTo", replyTo);
            return (MailProducerBuilder) this;
        }
        /**
         * The Subject of the message being sent. Note: Setting the subject in
         * the header takes precedence over this option. The option is a
         * <code>java.lang.String</code> type.
         */
        public MailProducerBuilder subject(String subject) {
            this.properties.put("subject", subject);
            return (MailProducerBuilder) this;
        }
        /**
         * Sets the To email address. Separate multiple email addresses with
         * comma. The option is a <code>java.lang.String</code> type.
         */
        public MailProducerBuilder to(String to) {
            this.properties.put("to", to);
            return (MailProducerBuilder) this;
        }
        /**
         * To use a custom org.apache.camel.component.mail.JavaMailSender for
         * sending emails. The option is a
         * <code>org.apache.camel.component.mail.JavaMailSender</code> type.
         */
        public MailProducerBuilder javaMailSender(Object javaMailSender) {
            this.properties.put("javaMailSender", javaMailSender);
            return (MailProducerBuilder) this;
        }
        /**
         * To use a custom org.apache.camel.component.mail.JavaMailSender for
         * sending emails. The option will be converted to a
         * <code>org.apache.camel.component.mail.JavaMailSender</code> type.
         */
        public MailProducerBuilder javaMailSender(String javaMailSender) {
            this.properties.put("javaMailSender", javaMailSender);
            return (MailProducerBuilder) this;
        }
    }
    /**
     * To send or receive emails using imap/pop3 or smtp protocols. Creates a
     * builder to build a consumer endpoint for the IMAP component.
     */
    public default MailConsumerBuilder fromMail(String path) {
        return new MailConsumerBuilder(path);
    }
    /**
     * To send or receive emails using imap/pop3 or smtp protocols. Creates a
     * builder to build a producer endpoint for the IMAP component.
     */
    public default MailProducerBuilder toMail(String path) {
        return new MailProducerBuilder(path);
    }
}