/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.model.endpoint;

import javax.annotation.Generated;

/**
 * To send passive checks to Nagios using JSendNSCA.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.EndpointDslMojo")
public class NagiosEndpoint {


    public static class NagiosCommon extends EndpointConfiguration {
        /**
         * This is the address of the Nagios host where checks should be send.
         * The option is a java.lang.String type.
         */
        private String host;
        /**
         * The port number of the host. The option is a int type.
         */
        private Integer port;
        /**
         * Connection timeout in millis. The option is a int type.
         */
        private Integer connectionTimeout;
        /**
         * Whether or not to use synchronous when sending a passive check.
         * Setting it to false will allow Camel to continue routing the message
         * and the passive check message will be send asynchronously. The option
         * is a boolean type.
         */
        private Boolean sendSync;
        /**
         * Sending timeout in millis. The option is a int type.
         */
        private Integer timeout;
        /**
         * Whether the endpoint should use basic property binding (Camel 2.x) or
         * the newer property binding with additional capabilities. The option
         * is a boolean type.
         */
        private Boolean basicPropertyBinding;
        /**
         * Sets whether synchronous processing should be strictly used, or Camel
         * is allowed to use asynchronous processing (if supported). The option
         * is a boolean type.
         */
        private Boolean synchronous;
        /**
         * To specify an encryption method. The option is a
         * com.googlecode.jsendnsca.encryption.Encryption type.
         */
        private Encryption encryption;
        /**
         * To specify an encryption method. The option is a
         * org.apache.camel.component.nagios.NagiosEncryptionMethod type.
         */
        @Deprecated
        private NagiosEncryptionMethod encryptionMethod;
        /**
         * Password to be authenticated when sending checks to Nagios. The
         * option is a java.lang.String type.
         */
        private String password;

        public String getHost() {
            return host;
        }

        public void setHost(String host) {
            this.host = host;
        }

        public Integer getPort() {
            return port;
        }

        public void setPort(Integer port) {
            this.port = port;
        }

        public Integer getConnectionTimeout() {
            return connectionTimeout;
        }

        public void setConnectionTimeout(Integer connectionTimeout) {
            this.connectionTimeout = connectionTimeout;
        }

        public Boolean getSendSync() {
            return sendSync;
        }

        public void setSendSync(Boolean sendSync) {
            this.sendSync = sendSync;
        }

        public Integer getTimeout() {
            return timeout;
        }

        public void setTimeout(Integer timeout) {
            this.timeout = timeout;
        }

        public Boolean getBasicPropertyBinding() {
            return basicPropertyBinding;
        }

        public void setBasicPropertyBinding(Boolean basicPropertyBinding) {
            this.basicPropertyBinding = basicPropertyBinding;
        }

        public Boolean getSynchronous() {
            return synchronous;
        }

        public void setSynchronous(Boolean synchronous) {
            this.synchronous = synchronous;
        }

        public Encryption getEncryption() {
            return encryption;
        }

        public void setEncryption(Encryption encryption) {
            this.encryption = encryption;
        }

        @Deprecated
        public NagiosEncryptionMethod getEncryptionMethod() {
            return encryptionMethod;
        }

        @Deprecated
        public void setEncryptionMethod(NagiosEncryptionMethod encryptionMethod) {
            this.encryptionMethod = encryptionMethod;
        }

        public String getPassword() {
            return password;
        }

        public void setPassword(String password) {
            this.password = password;
        }
    }

    public static class NagiosConsumer extends NagiosCommon {
    }

    public static class NagiosProducer extends NagiosCommon {
    }

    public static enum Encryption {
        NONE, TRIPLE_DES, XOR, RIJNDAEL128, RIJNDAEL192, RIJNDAEL256, BLOWFISH;
    }

    public static enum NagiosEncryptionMethod {
        No, Xor, TripleDes;
    }
}